### ISSUE TITLE
unable to pass argument to the spider in run_spider

### ISSUE THREAD

**Issue by jo11yn** [rolando/scrapydo#3]
a nice feature would be to be able to pass argument to our spider in run_spider api

this could be done in _run_spider_in_reactor
d = crawler.crawl(some_args)

**Comment by MTeani** [comment]
I haven't had a problems passing arguments to my spiders like so:

scrapydo.setup()
scrapydo.run_spider(MySpider(args=args))

**Comment by olivmaurel** [comment]
I had also this problem with my script. I tried to pass the arguments in the spider as suggested but it didn't work for me. I solved it with a modification in the api.py file. Basically, just add **kwargs in the _run_spider_in_reactor function, and in the line d = crawler.crawl(). The modified code looks like this
```
@crochet.run_in_reactor
def _run_spider_in_reactor(spider_cls, capture_items=True, return_crawler=False,
                           settings=None, **kwargs):
    settings = settings or {}
    crawler_settings = get_project_settings().copy()
    crawler_settings.setdict(settings)
    log_scrapy_info(crawler_settings)
    crawler = Crawler(spider_cls, crawler_settings)
    d = crawler.crawl(**kwargs)
    if capture_items:
        crawler.items = _OutputItems()
        crawler.signals.connect(crawler.items.append, signal=signals.item_scraped)
        d.addCallback(lambda _: crawler.items)
    if return_crawler:
        d.addCallback(lambda _: crawler)
    return d

``` 
then do
scrapydo.setup()
scrapydo.run_spider(MySpider(a='a', b='b'), a='a', b='b')

**Comment by jo11yn** [comment]
yes that's exactly what i suggested :)

**Comment by rmax** [comment]
Thanks for your input guys. I will retake this as soon as possible.

**Comment by rmax** [comment]
Feature added in last release as follows:

```
scrapydo.run_spider(MySpider, arg=value)
```
