### ISSUE TITLE
scrapydo.fetch() AttributeError

### ISSUE THREAD

**Issue by jbohannon** [rolando/scrapydo#7]
I'm trying scrapydo and can't even get started:

>>> import scrapydo
>>> scrapydo.setup()
>>> url = "http://google.com"
>>> scrapydo.fetch(url)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/john/anaconda/envs/py3/lib/python3.4/site-packages/scrapydo/api.py", line 51, in fetch
    return crawler.spider.response
AttributeError: 'DefaultSpider' object has no attribute 'response'

**Comment by olivmaurel** [comment]
DefaultSpider doesn't point to anything in the source code apparently. I think you need to define your own scrapy.Spider object and do 

import scrapydo
scrapydo.setup()
url = "http://google.com"
scrapydo.fetch(url, spider_cls=MySpider)

**Comment by rmax** [comment]
It seems the response callback is not called: https://github.com/rolando/scrapydo/blob/master/scrapydo/api.py#L139-L140

Either the URL is filtered out or returns an error. @jbohannon Did you tried other URLs?

**Comment by jbohannon** [comment]
Yep, no URL works.

**Comment by rmax** [comment]
Latest release does not throw that error. It fails silently which is not ideal but to be fixed in #9
